location:
  name: Guilford, CT
  latitude: 41.3345744
  longitude: -72.6732571
  timezone: America/New_York
display:
  columns: 12
  rows: 6
  units: imperial
widgets:
- id: datetime
  position:
    x: 4
    y: 0
    w: 4
    h: 2
- id: stocks
  position:
    x: 8
    y: 0
    w: 4
    h: 4
  config:
    symbols:
    - ^IXIC
    - ^GSPC
    - ^DJI
    - AAPL
    - GOOGL
    - MSFT
    - NVDA
    - TSLA
    refresh_interval: 60
- id: calendar
  position:
    x: 4
    y: 2
    w: 4
    h: 4
- id: cputemp
  position:
    x: 0
    y: 0
    w: 4
    h: 3
- id: weather
  position:
    x: 8
    y: 4
    w: 4
    h: 2
- id: cpu
  position:
    x: 0
    y: 3
    w: 4
    h: 2
- id: launcher
  position:
    x: 0
    y: 5
    w: 4
    h: 1
  config:
    items:
    - label: Config
      icon: ⚙️
      action: config
    - label: Terminal
      icon: 💻
      action: app
      command: gnome-terminal
    - label: Firefox
      icon: 🦊
      action: app
      command: firefox
