location:
  name: Guilford, CT
  latitude: 41.3345744
  longitude: -72.6732571
  timezone: America/New_York
display:
  columns: 12
  rows: 3
widgets:
- id: datetime
  position:
    x: 4
    y: 0
    w: 4
    h: 1
- id: stocks
  position:
    x: 8
    y: 0
    w: 4
    h: 2
  config:
    symbols:
    - ^IXIC
    - ^GSPC
    - ^DJI
    - AAPL
    - GOOGL
    - MSFT
    - NVDA
    - TSLA
    refresh_interval: 60
- id: calendar
  position:
    x: 4
    y: 1
    w: 4
    h: 2
- id: cpu
  position:
    x: 0
    y: 2
    w: 4
    h: 1
- id: cputemp
  position:
    x: 0
    y: 0
    w: 4
    h: 2
- id: weather
  position:
    x: 8
    y: 2
    w: 4
    h: 1
  config:
    units: imperial
